### ISSUE TITLE
Add playback buttons to wibbly video output

### ISSUE THREAD

**Issue by LightArrowsEXE** [Jaded-Encoding-Thaumaturgy/Wobbly#23]
After using avidemux a bit to trim DVD video, there are a handful of buttons I'm missing in wibbly that I think would be useful for speeding up the process of trimming clips.

### Jump to next/previous I frame

This may be possible to get from the file itself, but will need to be parsed.

### Jump to the next/previous black frame

Very useful for finding the end of an episode.

Of course these would require new buttons and keybinds too, but they can help speed up trimming if implemented.

Additionally, maybe highlighting in the playerbar for trimming would be nice, as well as keybinds to select a start/end time and a commit bind too.

**Comment by Setsugennoao** [comment]
As Wibbly is being put into its own subpackage in vsdeinterlace and vspreview plugin, I'm closing this as not planned.
