### ISSUE TITLE
interlaced fades: ignore gaps doesn't do anything meaningful

### ISSUE THREAD

**Issue by LightArrowsEXE** [Jaded-Encoding-Thaumaturgy/Wobbly#26]
There is an option to ignore gaps in the `interlaced fades` window, but this currently doesn't do anything useful (although it may sometimes round some values for some reason?)

```diff
"frame": 1314,
-"field difference": 0.025053393284442787
+"field difference": 0.02505339328444279
```

I think the best thing for it to do is to store the value passed in the wobbly file at the very least so these values can be utilised in scripts. If we want to still give it a use in Wobbly itself, I say we also add the frames that are now counted as an interlaced fades to the list of frames.

**Comment by Setsugennoao** [comment]
Can't repro
