### ISSUE TITLE
Certain keybinds only work if used with a numpad

### ISSUE THREAD

**Issue by wiwaz** [Jaded-Encoding-Thaumaturgy/Wobbly#27]
Wobbly only accepts some keys if they are used through a numpad instead of the normal keyboard layout. Includes keys such as: all numbers, plus, minus, etc. The default zoom keybind is unusable if you lack a numpad, for example.

**Comment by Setsugennoao** [comment]
I think all numpad keys got remapped/replaced and this is not an issue anymore.

**Comment by Setsugennoao** [comment]
@wiwaz why did you reopen?

**Comment by Setsugennoao** [comment]
I'm clearly asking what doesn't work for you, because when i tested both number and keypad worked
