### ISSUE TITLE
wobbly requires full path to output d2v files

### ISSUE THREAD

**Issue by nobananasforyou** [Jaded-Encoding-Thaumaturgy/Wobbly#9]
Wobbly won't open a d2v (indexed m2v) file unless it has been given the full path of the file. 

e.g.
rawr.d2v
C:\argh\rawr.d2v

**Comment by LightArrowsEXE** [comment]
This issue seems to persist with any kind of input. Support for relative paths would be appreciated, and maybe that can be an optional argument passed to the wibbly rewrite @Setsugennoao?

**Comment by Setsugennoao** [comment]
Can't repro
